package densh.com.iqhouse.view.ui.util

/**
 * Created by denglob on 9/10/17.
 */
val HEXAGON_INNER_RADIUS_DP = 50
val HEXAGON_EXTERIOR_RADIUS_DP = ((HEXAGON_INNER_RADIUS_DP * 2)/Math.sqrt(3.0)).toInt()
val HEXAGON_MARGIN_DP = 12

val SECOND_PART_SPACING = HEXAGON_INNER_RADIUS_DP / 4
val FIRST_PART_SPACING = HEXAGON_EXTERIOR_RADIUS_DP

val HEXAGON_HEIGHT = HEXAGON_EXTERIOR_RADIUS_DP * 2
val HEXAGON_WIDTH= HEXAGON_INNER_RADIUS_DP * 2
